import streamlit as st


st.title("About This Project")


st.markdown(
"""
# Chest X-ray Disease Classification Using Deep Learning

This project explores the application of deep learning for automated analysis 
of chest X-ray images. The goal is to develop a multi-label image 
classification system capable of identifying patterns associated with 
different thoracic diseases.

The system takes a chest X-ray image as input and predicts the probability 
of 14 different disease categories. Since a single X-ray can contain signs 
of multiple conditions at the same time, this is treated as a **multi-label 
classification problem** rather than a simple single-class prediction task.
"""
)


st.subheader("Problem Overview")

st.markdown(
"""
Chest X-ray interpretation requires significant expertise and can be challenging
due to subtle visual differences between normal and abnormal findings.

Deep learning models, especially convolutional neural networks (CNNs), have
shown potential in learning complex visual patterns from medical images.

This project investigates how transfer learning can be used to adapt a
pre-trained neural network for chest X-ray disease classification.
"""
)


st.subheader("Dataset")

st.markdown(
"""
The model is trained using the **NIH ChestX-ray14 dataset**, a large publicly
available collection of chest radiographs.

The dataset contains:

- Over 100,000 chest X-ray images
- 14 thoracic disease categories
- Multi-label annotations extracted from radiology reports

The disease categories include conditions such as:

- Atelectasis
- Cardiomegaly
- Consolidation
- Edema
- Effusion
- Infiltration
- Mass
- Nodule
- Pneumonia
- Pneumothorax
- And others

The dataset presents real-world challenges including class imbalance and
uncertain labels, making medical image classification a difficult task.
"""
)


st.subheader("Model Architecture")

st.markdown(
"""
The project uses **DenseNet121**, a convolutional neural network architecture
based on transfer learning.

Instead of training a deep neural network from scratch, the model starts with
weights learned from large-scale image datasets and is fine-tuned on chest
X-ray images.

DenseNet was selected because its dense connectivity pattern helps preserve
feature information through deeper layers and has been widely explored in
medical imaging research.
"""
)


st.subheader("Project Pipeline")

st.markdown(
"""
The complete workflow includes:

1. **Data Processing**
   - Cleaning and preparing dataset annotations
   - Converting disease labels into multi-label format
   - Applying image preprocessing and augmentation

2. **Model Training**
   - Fine-tuning DenseNet121 using PyTorch
   - Optimizing the model for multi-label classification

3. **Evaluation**
   - Measuring performance using:
       - AUROC
       - F1-score
       - Precision
       - Recall
       - Confusion matrices

4. **Deployment**
   - Creating an interactive web interface using Streamlit
   - Allowing users to upload chest X-ray images and view model predictions
"""
)


st.subheader("Technology Stack")

st.markdown(
"""
**Programming Language**
- Python

**Deep Learning**
- PyTorch
- Torchvision
- DenseNet121

**Data Processing & Evaluation**
- NumPy
- Pandas
- Scikit-learn
- Matplotlib

**Deployment**
- Streamlit
"""
)


st.subheader("Important Note")

st.warning(
"""
This application is developed for educational and research purposes only.
The predictions generated by this model should not be considered medical
diagnosis or used for clinical decision-making.
"""
)